# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: bookexchange
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: bookexchange_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: bookexchange
      DB_PASSWORD: securepassword
      DB_NAME: bookexchange_db
      JWT_SECRET: your_jwt_secret
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["./main"]

volumes:
  db_data:
